GET http://localhost:3000/users

###

GET http://localhost:3000/users/15


# practice
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "zaif",
  "email": "zaif@example.com"
}

PATCH http://localhost:3000/users/15
Content-Type: application/json

{
  "name": "zaif Updated"
}

DELETE http://localhost:3000/users/15
